name: conditions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: github.ref == 'refs/heads/feature-**'
        run: echo "This runs only on feature branch!"

      - name: step2
        if: github.ref == 'refs/heads/main'
        run: echo "This runs only on main branch!"

      
